### ISSUE TITLE
The graph explorer is not fully loaded

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdbgraph#6]
**OS:** Win10
**Build Version:** 20200711.5
**VS Code Version:** 1.47.0

**Repro Steps:**

1. Drill down  a Gremlin (graph) account --> Database --> Graph.
2. Click Graph --> Pop up a dialog --> Click "View Extension" --> Install Cosmos DB Graph extension.
4. Click on the graph in the tree.

**Expect:**
The graph explorer shows up as the below:
![image](https://user-images.githubusercontent.com/62053665/87287571-d621e580-c52c-11ea-9399-f6dd58f19269.png)

**Actual:**
The graph explorer shows up as the below:
![image](https://user-images.githubusercontent.com/62053665/87287628-ea65e280-c52c-11ea-85a1-d5f041453e4d.png)

**More info:**
This issue doesn't reproduce on Mac/Linux.

**Comment by sanchez** [comment]
Also have noticed the same issue on Windows. Is it possible to use a previous version of the extension until this is fixed? Thanks

**Comment by pvillads** [comment]
This extension is quite useless until this is fixed. How can you not fix it with extreme urgency? The value that your extension is supposed to provide is completely broken.

**Comment by jinglouMSFT** [comment]
@pvillads We prioritize all bugs and bug fixes among all extensions we own and work on.  This issue is slotted to be worked in the next couple of weeks because of the low usage of the extension. Thank you for your reminder and the comments.
Also, we encourage users to use Gremlin in Azure portal where they have a much better coverage and a richer experiences.
